import esbuild from "esbuild";
import process from "process";
import path from "path";
import builtins from "builtin-modules";
import { copyStaticFiles, ensureDevVault, getDevPluginDir } from "./scripts/setup-dev-vault.mjs";
import { syncToAllVaults } from "./scripts/sync-to-vault.mjs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const mode = process.argv[2];
const prod = mode === "production";
const devOnce = mode === "dev-once";
const isDev = !prod;

if (isDev) {
	ensureDevVault();
}

const outfile = prod
	? path.join(".", "main.js")
	: path.join(getDevPluginDir(), "main.js");

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile,
	minify: prod,
	plugins: [{
		name: "dev-static-files",
		setup(build) {
			build.onEnd((result) => {
				if (isDev && result.errors.length === 0) {
					copyStaticFiles();
					try {
						syncToAllVaults(getDevPluginDir());
					} catch (e) {
						console.warn(String(e));
					}
				}
			});
		},
	}],
});

if (prod || devOnce) {
	await context.rebuild();
	process.exit(0);
}

await context.watch();
